# Generated by Django 3.2 on 2021-04-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_order_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
